# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b0a30cd4cff61dae8d7efbdfebef75a1d12815f0c7af79e289022a70ab9cfba1258ee11a8c7c7a55287a9cff915020bec3c879456b456641d42cfc124ae79d4

test:
  secret_key_base: 09f35076716c909d4d27cd1257ec38f79ca5ba874cb8d33956fbfb67883de08af5ca37c7f661fbeda2c8790a4a24be69c51086557b323c24e0cabb41ba685e61

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
